//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Ejercicio1Result del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ejercicio1", ReplyAction="*")]
        WindowsFormsApp1.ServiceReference1.Ejercicio1Response Ejercicio1(WindowsFormsApp1.ServiceReference1.Ejercicio1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ejercicio1", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Ejercicio1Response> Ejercicio1Async(WindowsFormsApp1.ServiceReference1.Ejercicio1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ejercicio1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ejercicio1", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.Ejercicio1RequestBody Body;
        
        public Ejercicio1Request() {
        }
        
        public Ejercicio1Request(WindowsFormsApp1.ServiceReference1.Ejercicio1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ejercicio1RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ci;
        
        public Ejercicio1RequestBody() {
        }
        
        public Ejercicio1RequestBody(int ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Ejercicio1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ejercicio1Response", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp1.ServiceReference1.Ejercicio1ResponseBody Body;
        
        public Ejercicio1Response() {
        }
        
        public Ejercicio1Response(WindowsFormsApp1.ServiceReference1.Ejercicio1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Ejercicio1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Data.DataSet Ejercicio1Result;
        
        public Ejercicio1ResponseBody() {
        }
        
        public Ejercicio1ResponseBody(System.Data.DataSet Ejercicio1Result) {
            this.Ejercicio1Result = Ejercicio1Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WindowsFormsApp1.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.WebServiceSoap>, WindowsFormsApp1.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference1.Ejercicio1Response WindowsFormsApp1.ServiceReference1.WebServiceSoap.Ejercicio1(WindowsFormsApp1.ServiceReference1.Ejercicio1Request request) {
            return base.Channel.Ejercicio1(request);
        }
        
        public System.Data.DataSet Ejercicio1(int ci) {
            WindowsFormsApp1.ServiceReference1.Ejercicio1Request inValue = new WindowsFormsApp1.ServiceReference1.Ejercicio1Request();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.Ejercicio1RequestBody();
            inValue.Body.ci = ci;
            WindowsFormsApp1.ServiceReference1.Ejercicio1Response retVal = ((WindowsFormsApp1.ServiceReference1.WebServiceSoap)(this)).Ejercicio1(inValue);
            return retVal.Body.Ejercicio1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Ejercicio1Response> WindowsFormsApp1.ServiceReference1.WebServiceSoap.Ejercicio1Async(WindowsFormsApp1.ServiceReference1.Ejercicio1Request request) {
            return base.Channel.Ejercicio1Async(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Ejercicio1Response> Ejercicio1Async(int ci) {
            WindowsFormsApp1.ServiceReference1.Ejercicio1Request inValue = new WindowsFormsApp1.ServiceReference1.Ejercicio1Request();
            inValue.Body = new WindowsFormsApp1.ServiceReference1.Ejercicio1RequestBody();
            inValue.Body.ci = ci;
            return ((WindowsFormsApp1.ServiceReference1.WebServiceSoap)(this)).Ejercicio1Async(inValue);
        }
    }
}
